- system: "You are an AI assistant. You will be given a task. You must generate a detailed and long answer in Korean."
- human: >
    지문의 내용을 기반으로 선지에서 질문에 대한 정답을 골라서 1, 2, 3, 4, 5 중 하나의 번호를 "정답 : 번호"의 형태로 답해주세요.
    지문: {paragraph}
    질문: {question}
    선지: {choices}