# seed
seed: 
  42

# wandb
project:
  "DongHyeok"
sub_project:
  "exaoneTest"

# data path
data_dir:
  "./data" 
train_path:
  "v0.1.6/train_v0.1.6.csv"
val_path:
  "val_v0.1.6.csv"
output_file:
  "inference_results.csv"

# dataset
max_length:
  2048

# data collector
response_template: # Model이 답할 부분에 대한 템플릿 시작
  "[|assistant|]"

# tokenizer
padding_side:
  'right'

# model
train_model_path_or_name: 
  "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct"
test_model_path_or_name:
  "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct/checkpoint-1293"

# SFT
num_train_epochs: 3
learning_rate: 0.00001
weight_decay: 0.01
logging_steps: 100
save_total_limit : 2

# LoRa
rank: 4
lora_alpha: 16
lora_dropout : 0.05
target_modules: 
  - "q_proj"  
  - "k_proj"
bias : "none"
task_type : "CAUSAL_LM"

# prompt
PROMPT_NO_QUESTION_PLUS: >
  다음의 절차대로 문제를 풀어서 답을 골라줘.

  1. 문제를 분석하여 정보를 파악해줘
  2. 질문을 분석하여 1번에서 관련 된 정보만 정리해줘
  3. 선지를 분석하여 2번에 관련된 정보로 답을 골라줘

  지문:
  {paragraph}

  질문:
  {question}

  선택지:
  {choices}

  1, 2, 3, 4, 5 중에 하나를 정답으로 고르세요.
  이유:
  정답:

PROMPT_QUESTION_PLUS: >
  다음의 절차대로 문제를 풀어서 답을 골라줘.

  1. 문제를 분석하여 정보를 파악해줘
  2. 질문을 분석하여 1번에서 관련 된 정보만 정리해줘
  3. 선지를 분석하여 2번에 관련된 정보로 답을 골라줘

  지문:
  {paragraph}

  질문:
  {question}

  <보기>:
  {question_plus}

  선택지:
  {choices}

  1, 2, 3, 4, 5 중에 하나를 정답으로 고르세요.
  이유:
  정답:

chat_template: >
  {% for message in messages %}
    {% if loop.first and message['role'] != 'system' %}
      {{ '[|system|][|endofturn|]' }}
    {% endif %}
    {{ '[|' + message['role'] + '|]' + message['content'] }}
    {% if message['role'] == 'user' %}
      {{ '' }}
    {% else %}
    {{ '[|endofturn|]' }}
    {% endif %}
  {% endfor %}
  {% if add_generation_prompt %}
    {{ '[|assistant|]' }}
  {% endif %}