seed:
  42
# wandb
project:
  "LeeJeonge"
sub_project:
  "qwen_32_finetuning_CoT"

# data path
data_dir:
  "./data" 
train_path:
  "v0.1.6/train.csv"
val_path:
  "v0.1.6/val.csv"
output_file:
  "inference_results.csv"

# dataset
max_length:
  4096

# data collector
response_template: # Model이 답할 부분에 대한 템플릿 시작
  "<|im_start|>assistant\n"

# tokenizer
padding_side:
  'right'

# model
train_model_path_or_name: 
  "unsloth/Qwen2.5-32B-Instruct-bnb-4bit"
test_model_path_or_name:
  "unsloth/Qwen2.5-32B-Instruct-bnb-4bit"

# SFT
num_train_epochs: 1
learning_rate: 0.00001
weight_decay: 0.01
logging_steps: 100
save_total_limit : 2

# LoRa
rank: 4
lora_alpha: 16
lora_dropout : 0.1
target_modules: 
  - "q_proj"  
  - "k_proj"
bias : "none"
task_type : "CAUSAL_LM"

PROMPT_SYSTEM_MESSAGE: >
  당신은 전교 1등 학생입니다. 지문, 질문을 읽고 선택지에서 정답을 구하세요.
# prompt
PROMPT_NO_QUESTION_PLUS: >
  지문을 자세히 이해하고, 질문에 대하여 선택지 중 옳은 정답을 선택하세요.
  제공된 힌트를 참고하여 정답을 선택하세요. 정답은 선택지에서 정답인 인덱스를 출력하세요.
  
  ### 예제 1
  지문:학교 심리학자인 Mr.Thomas 씨는 특수 교육 교사인 Ms.Riddle과 협력하여 자폐 스펙트럼 장애가 있는 학생인 Mark의 요구를 충족하려고합니다.Mr.Thomas 씨가 Mark와 직접적으로 접촉하는 대신,Ms.Riddle이 그의 중재자 역할을 합니다.

  질문:이러한 협업은 어떤 상담 모델의 예시입니까?

  선택지:
  1 - 체계
  2 - 자원
  3 - 3 축(triadic)
  4 - 적응형 학습 환경

  정답: 3

  ### 예제 2
  지문:“여기서 생기는 한 가지 의문은 사랑을 받는 것이 두려움의 대상이 되는 것보다 나은가 아니면 그 반대인가 하는 것입니다. 둘 다를 바란다고 대답할 수 있겠으나 한 사람이 둘 모두를 가지기는 어렵기 때문에 둘 중 하나를 제거해야하는 경우 사랑을 받는 것 보다 두려움의 대상이 되는 것이 훨씬 안전합니다. 왜냐하면 이것은 일반적으로 인간에 대해 주장되어야하는 것으로 인간은 배은망덕하고, 변덕스러우며, 거짓을 일삼고, 겁이 많고, 탐욕스럽기 때문입니다. 또한 당신이 성공한다면 이들은 모두 당신의 것입니다. 앞서 말한 바와 같이 필요한 것을 즉시 얻을 수 없을 경우 이들은 피와 재산과 생명과 아이들까지도 당신에게 바칠 것입니다. 하지만 원하는 걸 거의 얻어 냈다면 당신을 배반할 것입니다. 그리고 전적으로 약속에만 의존하고 다른 예방 조치를 소홀히 한 군주는 파멸합니다. 위대함이나 고결한 정신이 아닌 돈으로 산 우정은 얻을 수는 있으나 보장되지는 않으며 정작 필요한 때에 의지할 수 없습니다. 인간은 사랑하는 사람을 화나게하는 것보다 두려워하는 사람을 화나게하는 일을 어렵게 생각합니다. 사랑은 의무의 연결로 보존되며 인간의 본성에 따라 자신의 이득을 위해 이 연결을 얼마든지 끊어 낼 수 있지만 두려움은 절대 실패할 수 없는 처벌에 대한 공포로 당신을 지켜 주기 때문입니다.”

  질문:위 글에서 주장하는 정치 철학은 중세 시대의 철학과 다음에 나열된 것 중 어떤 면에서 다른가요?

  선택지:
  1 - 군주가 자신의 권위를 주장하는 것이 정당하다는 개념을 받아들였다.
  2 - 윤리 또는 종교적 이념보다는 실용주의적 이념이었다.
  3 - 고전적인 과거를 돌아보는 것의 중요성을 강조했다.
  4 - 계층 간 경계를 초월하는 평등이라는 강력한 개념에 의존하지 않았다.

  정답: 2
  
  ### 예제 3
  지문:‘왓츠앱’(사진)‘아이 메시지’등 대화용 애플리케이션(앱· 응용 프로그램)이 빠르게 성장하면서 이동 통신 업계의‘캐시카우(현금 창출 원)’인 문자 메시지 시장을 잠식하고 있다고 파이낸셜타임스(FT)가 29일 보도했다. 통신· 미디어 전문 컨설팅 회사인 인 포 마의 조사 결과에 따르면 대화용 앱을 이용한 하루 메시지 전송 건수가 작년 말 문자 메시지 전송 건수를 추월한 것으로 나타났다.5년 전에는 존재하지도 않았던 대화용 앱이 이제는 페이스북 등 소셜 네트워크 서비스(SNS)의 아성까지 위협하고 있다고 FT는 분석했다 .인포마는 올해 대화용 앱을 이용한 메시지 전송 건수가 문자 메시지 전송 건수의 두 배가 넘는 410 억 건에 달할 것으로 전망했다. 올해 문자 메시지 시장에서만 1200 억 달러 이상의 수익을 낼 것으로 보이는 이동 통신 업계의 수익성에 상당한 영향을 끼칠 것으로인 포 마는 내다봤다. 특히 문자 메시지뿐 아니라 동영상, 인터넷을 통한 음성 통화 서비스 등 통신 업계의 핵심 사업 영역을 침범할 것이라는 분석이다. 이런 변화는 한국을 비롯해 스페인, 네덜란드 같은 나라의 이동 통신 사업자에게 큰 영향을 끼치고 있다. 예를 들어 스페인은 문자 메시지로 인한 수익이 2007년 11 억 유로에 달했으나 2011년에는 7 억 5850 만 유로로 줄었다. 전송 량도 2007년 95 억 건에서 2011년에는 74 억 건으로 떨어졌다.5000 만 명의 사용자를 보유하고 있는 대화용 앱‘킥(Kik)’의 테드 리빙스턴 최고 경영자(CEO)는“앞으로는 사람들이 휴대폰 데이터 요금제를 바꿀 때 문자 메시지 서비스는 반드시 없애는 항목이 될 것”이라고 말했다. 리빙스턴은“만약 내가 똑같은 상품을 놓고 하나는 무료인데 하나는 돈을 내야한다면 당연히 전자를 선택할 것”이라고 지적했다.

  질문:대화용 애플리케이션의 성장으로 인해 어떤 시장이 잠식되고 있는가?

  선택지:
  1 - 문자 메시지 시장
  2 - 음성 통화 시장
  3 - 동영상 스트리밍 시장
  4 - 소셜 네트워크 서비스 시장
  5 - 이동 통신 장비 시장

  정답: 1

  ### 문제
  선택지에서 정답인 인덱스만 출력하세요. 
  출력은 반드시 '정답: {{숫자}}' 포맷으로 출력합니다. (1~5점으로 예측하세요.)
  
  지문:
  {paragraph}

  질문:
  {question}

  선택지:
  {choices}

  정답:
PROMPT_QUESTION_PLUS: >
  지문을 자세히 이해하고, 질문에 대하여 선택지 중 옳은 정답을 선택하세요.
  제공된 힌트를 참고하여 정답을 선택하세요. 정답은 선택지에서 정답인 인덱스를 출력하세요.

  ### 예제 1
  지문:학교 심리학자인 Mr.Thomas 씨는 특수 교육 교사인 Ms.Riddle과 협력하여 자폐 스펙트럼 장애가 있는 학생인 Mark의 요구를 충족하려고합니다.Mr.Thomas 씨가 Mark와 직접적으로 접촉하는 대신,Ms.Riddle이 그의 중재자 역할을 합니다.

  질문:이러한 협업은 어떤 상담 모델의 예시입니까?

  선택지:
  1 - 체계
  2 - 자원
  3 - 3 축(triadic)
  4 - 적응형 학습 환경

  정답: 3

  ### 예제 2
  지문:“여기서 생기는 한 가지 의문은 사랑을 받는 것이 두려움의 대상이 되는 것보다 나은가 아니면 그 반대인가 하는 것입니다. 둘 다를 바란다고 대답할 수 있겠으나 한 사람이 둘 모두를 가지기는 어렵기 때문에 둘 중 하나를 제거해야하는 경우 사랑을 받는 것 보다 두려움의 대상이 되는 것이 훨씬 안전합니다. 왜냐하면 이것은 일반적으로 인간에 대해 주장되어야하는 것으로 인간은 배은망덕하고, 변덕스러우며, 거짓을 일삼고, 겁이 많고, 탐욕스럽기 때문입니다. 또한 당신이 성공한다면 이들은 모두 당신의 것입니다. 앞서 말한 바와 같이 필요한 것을 즉시 얻을 수 없을 경우 이들은 피와 재산과 생명과 아이들까지도 당신에게 바칠 것입니다. 하지만 원하는 걸 거의 얻어 냈다면 당신을 배반할 것입니다. 그리고 전적으로 약속에만 의존하고 다른 예방 조치를 소홀히 한 군주는 파멸합니다. 위대함이나 고결한 정신이 아닌 돈으로 산 우정은 얻을 수는 있으나 보장되지는 않으며 정작 필요한 때에 의지할 수 없습니다. 인간은 사랑하는 사람을 화나게하는 것보다 두려워하는 사람을 화나게하는 일을 어렵게 생각합니다. 사랑은 의무의 연결로 보존되며 인간의 본성에 따라 자신의 이득을 위해 이 연결을 얼마든지 끊어 낼 수 있지만 두려움은 절대 실패할 수 없는 처벌에 대한 공포로 당신을 지켜 주기 때문입니다.”

  질문:위 글에서 주장하는 정치 철학은 중세 시대의 철학과 다음에 나열된 것 중 어떤 면에서 다른가요?

  선택지:
  1 - 군주가 자신의 권위를 주장하는 것이 정당하다는 개념을 받아들였다.
  2 - 윤리 또는 종교적 이념보다는 실용주의적 이념이었다.
  3 - 고전적인 과거를 돌아보는 것의 중요성을 강조했다.
  4 - 계층 간 경계를 초월하는 평등이라는 강력한 개념에 의존하지 않았다.

  정답: 2

  ### 예제 3
  지문:‘왓츠앱’(사진)‘아이 메시지’등 대화용 애플리케이션(앱· 응용 프로그램)이 빠르게 성장하면서 이동 통신 업계의‘캐시카우(현금 창출 원)’인 문자 메시지 시장을 잠식하고 있다고 파이낸셜타임스(FT)가 29일 보도했다. 통신· 미디어 전문 컨설팅 회사인 인 포 마의 조사 결과에 따르면 대화용 앱을 이용한 하루 메시지 전송 건수가 작년 말 문자 메시지 전송 건수를 추월한 것으로 나타났다.5년 전에는 존재하지도 않았던 대화용 앱이 이제는 페이스북 등 소셜 네트워크 서비스(SNS)의 아성까지 위협하고 있다고 FT는 분석했다 .인포마는 올해 대화용 앱을 이용한 메시지 전송 건수가 문자 메시지 전송 건수의 두 배가 넘는 410 억 건에 달할 것으로 전망했다. 올해 문자 메시지 시장에서만 1200 억 달러 이상의 수익을 낼 것으로 보이는 이동 통신 업계의 수익성에 상당한 영향을 끼칠 것으로인 포 마는 내다봤다. 특히 문자 메시지뿐 아니라 동영상, 인터넷을 통한 음성 통화 서비스 등 통신 업계의 핵심 사업 영역을 침범할 것이라는 분석이다. 이런 변화는 한국을 비롯해 스페인, 네덜란드 같은 나라의 이동 통신 사업자에게 큰 영향을 끼치고 있다. 예를 들어 스페인은 문자 메시지로 인한 수익이 2007년 11 억 유로에 달했으나 2011년에는 7 억 5850 만 유로로 줄었다. 전송 량도 2007년 95 억 건에서 2011년에는 74 억 건으로 떨어졌다.5000 만 명의 사용자를 보유하고 있는 대화용 앱‘킥(Kik)’의 테드 리빙스턴 최고 경영자(CEO)는“앞으로는 사람들이 휴대폰 데이터 요금제를 바꿀 때 문자 메시지 서비스는 반드시 없애는 항목이 될 것”이라고 말했다. 리빙스턴은“만약 내가 똑같은 상품을 놓고 하나는 무료인데 하나는 돈을 내야한다면 당연히 전자를 선택할 것”이라고 지적했다.

  질문:대화용 애플리케이션의 성장으로 인해 어떤 시장이 잠식되고 있는가?

  선택지:
  1 - 문자 메시지 시장
  2 - 음성 통화 시장
  3 - 동영상 스트리밍 시장
  4 - 소셜 네트워크 서비스 시장
  5 - 이동 통신 장비 시장

  정답: 1

  ### 문제
  선택지에서 정답인 인덱스만 출력하세요. 
  출력은 반드시 '정답: {{숫자}}' 포맷으로 출력합니다. (1~5점으로 예측하세요.)

  지문:
  {paragraph}

  질문:
  {question}

  보기:
  {question_plus}

  선택지:
  {choices}

  정답:
chat_template: null