# seed
seed: 
  42

# wandb
project:
  "RAG-Korean_Textbooks"
sub_project:
  "ft_qk16_rewriteQ800_v0.1.6"

# data path
data_dir:
  "../../data" 
train_path:
  "v0.1.6/train_v0.1.6.csv"
val_path:
  "v0.1.6/val_v0.1.6.csv"
output_file:
  "rag_train_top1.csv"

# for filtering dataset & setting model's max_length
max_length:
  4096

# data collector
response_template:
  "[|assistant|]"
  # "<start_of_turn>model"

# tokenizer
padding_side:
  'right'

# model
train_model_path_or_name: 
  "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct"
  # "beomi/gemma-ko-2b"
test_model_path_or_name:
  "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct"

# SFT
num_train_epochs: 2
learning_rate: 2e-5
weight_decay: 0.01
logging_steps: 1
save_total_limit : 2

# LoRa
rank: 16
lora_alpha: 16
lora_dropout : 0.05
target_modules: 
  - "q_proj"
  - "k_proj"
bias : "none"
task_type : "CAUSAL_LM"

# prompt
SYSTEM_PROMPT:
  "당신은 전교 1등 학생입니다. 지문을 읽고 질문에 해당하는 선택지를 고르세요. 힌트가 있다면 힌트를 참고하고, 정답 선지 번호만 출력하세요."
PROMPT_NO_QUESTION_PLUS: >
  ### 예제 1
  지문:학교 심리학자인 Mr.Thomas 씨는 특수 교육 교사인 Ms.Riddle과 협력하여 자폐 스펙트럼 장애가 있는 학생인 Mark의 요구를 충족하려고합니다.Mr.Thomas 씨가 Mark와 직접적으로 접촉하는 대신,Ms.Riddle이 그의 중재자 역할을 합니다.

  질문:이러한 협업은 어떤 상담 모델의 예시입니까?

  선택지:
  1 - 체계
  2 - 자원
  3 - 3 축(triadic)
  4 - 적응형 학습 환경

  정답: 3

  ### 예제 2
  지문:“여기서 생기는 한 가지 의문은 사랑을 받는 것이 두려움의 대상이 되는 것보다 나은가 아니면 그 반대인가 하는 것입니다. 둘 다를 바란다고 대답할 수 있겠으나 한 사람이 둘 모두를 가지기는 어렵기 때문에 둘 중 하나를 제거해야하는 경우 사랑을 받는 것 보다 두려움의 대상이 되는 것이 훨씬 안전합니다. 왜냐하면 이것은 일반적으로 인간에 대해 주장되어야하는 것으로 인간은 배은망덕하고, 변덕스러우며, 거짓을 일삼고, 겁이 많고, 탐욕스럽기 때문입니다. 또한 당신이 성공한다면 이들은 모두 당신의 것입니다. 앞서 말한 바와 같이 필요한 것을 즉시 얻을 수 없을 경우 이들은 피와 재산과 생명과 아이들까지도 당신에게 바칠 것입니다. 하지만 원하는 걸 거의 얻어 냈다면 당신을 배반할 것입니다. 그리고 전적으로 약속에만 의존하고 다른 예방 조치를 소홀히 한 군주는 파멸합니다. 위대함이나 고결한 정신이 아닌 돈으로 산 우정은 얻을 수는 있으나 보장되지는 않으며 정작 필요한 때에 의지할 수 없습니다. 인간은 사랑하는 사람을 화나게하는 것보다 두려워하는 사람을 화나게하는 일을 어렵게 생각합니다. 사랑은 의무의 연결로 보존되며 인간의 본성에 따라 자신의 이득을 위해 이 연결을 얼마든지 끊어 낼 수 있지만 두려움은 절대 실패할 수 없는 처벌에 대한 공포로 당신을 지켜 주기 때문입니다.”

  질문:위 글에서 주장하는 정치 철학은 중세 시대의 철학과 다음에 나열된 것 중 어떤 면에서 다른가요?

  선택지:
  1 - 군주가 자신의 권위를 주장하는 것이 정당하다는 개념을 받아들였다.
  2 - 윤리 또는 종교적 이념보다는 실용주의적 이념이었다.
  3 - 고전적인 과거를 돌아보는 것의 중요성을 강조했다.
  4 - 계층 간 경계를 초월하는 평등이라는 강력한 개념에 의존하지 않았다.

  정답: 2

  ### 문제 
  지문:
  {paragraph}

  질문: {question}

  선택지: {choices}

  정답:

PROMPT_QUESTION_PLUS: >
  ### 예제 1
  지문:학교 심리학자인 Mr.Thomas 씨는 특수 교육 교사인 Ms.Riddle과 협력하여 자폐 스펙트럼 장애가 있는 학생인 Mark의 요구를 충족하려고합니다.Mr.Thomas 씨가 Mark와 직접적으로 접촉하는 대신,Ms.Riddle이 그의 중재자 역할을 합니다.

  질문:이러한 협업은 어떤 상담 모델의 예시입니까?

  선택지:
  1 - 체계
  2 - 자원
  3 - 3 축(triadic)
  4 - 적응형 학습 환경

  정답: 3

  ### 예제 2
  지문:“여기서 생기는 한 가지 의문은 사랑을 받는 것이 두려움의 대상이 되는 것보다 나은가 아니면 그 반대인가 하는 것입니다. 둘 다를 바란다고 대답할 수 있겠으나 한 사람이 둘 모두를 가지기는 어렵기 때문에 둘 중 하나를 제거해야하는 경우 사랑을 받는 것 보다 두려움의 대상이 되는 것이 훨씬 안전합니다. 왜냐하면 이것은 일반적으로 인간에 대해 주장되어야하는 것으로 인간은 배은망덕하고, 변덕스러우며, 거짓을 일삼고, 겁이 많고, 탐욕스럽기 때문입니다. 또한 당신이 성공한다면 이들은 모두 당신의 것입니다. 앞서 말한 바와 같이 필요한 것을 즉시 얻을 수 없을 경우 이들은 피와 재산과 생명과 아이들까지도 당신에게 바칠 것입니다. 하지만 원하는 걸 거의 얻어 냈다면 당신을 배반할 것입니다. 그리고 전적으로 약속에만 의존하고 다른 예방 조치를 소홀히 한 군주는 파멸합니다. 위대함이나 고결한 정신이 아닌 돈으로 산 우정은 얻을 수는 있으나 보장되지는 않으며 정작 필요한 때에 의지할 수 없습니다. 인간은 사랑하는 사람을 화나게하는 것보다 두려워하는 사람을 화나게하는 일을 어렵게 생각합니다. 사랑은 의무의 연결로 보존되며 인간의 본성에 따라 자신의 이득을 위해 이 연결을 얼마든지 끊어 낼 수 있지만 두려움은 절대 실패할 수 없는 처벌에 대한 공포로 당신을 지켜 주기 때문입니다.”

  질문:위 글에서 주장하는 정치 철학은 중세 시대의 철학과 다음에 나열된 것 중 어떤 면에서 다른가요?

  선택지:
  1 - 군주가 자신의 권위를 주장하는 것이 정당하다는 개념을 받아들였다.
  2 - 윤리 또는 종교적 이념보다는 실용주의적 이념이었다.
  3 - 고전적인 과거를 돌아보는 것의 중요성을 강조했다.
  4 - 계층 간 경계를 초월하는 평등이라는 강력한 개념에 의존하지 않았다.

  정답: 2

  ### 문제 
  지문:
  {paragraph}

  질문: {question}

  <보기>:
  {question_plus}

  선택지: {choices}

  정답:

# tokenizer의 기본 template을 사용하고 싶다면 null로 표시해주세요.
chat_template: null

# RAG
database_path:
  "/data/ephemeral/home/data/v3/milvus_vector_db.db"
collection_name:
  "korean_textbooks"
rag_model_path_or_name: "dragonkue/bge-m3-ko"
rag_flag: 800
top_k: 1
use_k:
  - 1
rewrite_prefix: 
  "다음 정보를 바탕으로, 질문의 의도를 명확히 하여 검색에 적합한 질문을 작성하세요."
rewrite_model:
  'eenzeenee/t5-base-korean-summarization'

RAG_PROMPT_NO_QUESTION_PLUS: >
  ### 예제 1
  지문:학교 심리학자인 Mr.Thomas 씨는 특수 교육 교사인 Ms.Riddle과 협력하여 자폐 스펙트럼 장애가 있는 학생인 Mark의 요구를 충족하려고합니다.Mr.Thomas 씨가 Mark와 직접적으로 접촉하는 대신,Ms.Riddle이 그의 중재자 역할을 합니다.

  질문:이러한 협업은 어떤 상담 모델의 예시입니까?

  선택지:
  1 - 체계
  2 - 자원
  3 - 3 축(triadic)
  4 - 적응형 학습 환경

  정답: 3

  ### 예제 2
  지문:“여기서 생기는 한 가지 의문은 사랑을 받는 것이 두려움의 대상이 되는 것보다 나은가 아니면 그 반대인가 하는 것입니다. 둘 다를 바란다고 대답할 수 있겠으나 한 사람이 둘 모두를 가지기는 어렵기 때문에 둘 중 하나를 제거해야하는 경우 사랑을 받는 것 보다 두려움의 대상이 되는 것이 훨씬 안전합니다. 왜냐하면 이것은 일반적으로 인간에 대해 주장되어야하는 것으로 인간은 배은망덕하고, 변덕스러우며, 거짓을 일삼고, 겁이 많고, 탐욕스럽기 때문입니다. 또한 당신이 성공한다면 이들은 모두 당신의 것입니다. 앞서 말한 바와 같이 필요한 것을 즉시 얻을 수 없을 경우 이들은 피와 재산과 생명과 아이들까지도 당신에게 바칠 것입니다. 하지만 원하는 걸 거의 얻어 냈다면 당신을 배반할 것입니다. 그리고 전적으로 약속에만 의존하고 다른 예방 조치를 소홀히 한 군주는 파멸합니다. 위대함이나 고결한 정신이 아닌 돈으로 산 우정은 얻을 수는 있으나 보장되지는 않으며 정작 필요한 때에 의지할 수 없습니다. 인간은 사랑하는 사람을 화나게하는 것보다 두려워하는 사람을 화나게하는 일을 어렵게 생각합니다. 사랑은 의무의 연결로 보존되며 인간의 본성에 따라 자신의 이득을 위해 이 연결을 얼마든지 끊어 낼 수 있지만 두려움은 절대 실패할 수 없는 처벌에 대한 공포로 당신을 지켜 주기 때문입니다.”

  질문:위 글에서 주장하는 정치 철학은 중세 시대의 철학과 다음에 나열된 것 중 어떤 면에서 다른가요?

  선택지:
  1 - 군주가 자신의 권위를 주장하는 것이 정당하다는 개념을 받아들였다.
  2 - 윤리 또는 종교적 이념보다는 실용주의적 이념이었다.
  3 - 고전적인 과거를 돌아보는 것의 중요성을 강조했다.
  4 - 계층 간 경계를 초월하는 평등이라는 강력한 개념에 의존하지 않았다.

  정답: 2

  ### 문제 
  지문:
  {paragraph}

  질문: {question}

  선택지: {choices}

  힌트:
  {hint}

  정답:

RAG_PROMPT_QUESTION_PLUS: >
  ### 예제 1
  지문:학교 심리학자인 Mr.Thomas 씨는 특수 교육 교사인 Ms.Riddle과 협력하여 자폐 스펙트럼 장애가 있는 학생인 Mark의 요구를 충족하려고합니다.Mr.Thomas 씨가 Mark와 직접적으로 접촉하는 대신,Ms.Riddle이 그의 중재자 역할을 합니다.

  질문:이러한 협업은 어떤 상담 모델의 예시입니까?

  선택지:
  1 - 체계
  2 - 자원
  3 - 3 축(triadic)
  4 - 적응형 학습 환경

  정답: 3

  ### 예제 2
  지문:“여기서 생기는 한 가지 의문은 사랑을 받는 것이 두려움의 대상이 되는 것보다 나은가 아니면 그 반대인가 하는 것입니다. 둘 다를 바란다고 대답할 수 있겠으나 한 사람이 둘 모두를 가지기는 어렵기 때문에 둘 중 하나를 제거해야하는 경우 사랑을 받는 것 보다 두려움의 대상이 되는 것이 훨씬 안전합니다. 왜냐하면 이것은 일반적으로 인간에 대해 주장되어야하는 것으로 인간은 배은망덕하고, 변덕스러우며, 거짓을 일삼고, 겁이 많고, 탐욕스럽기 때문입니다. 또한 당신이 성공한다면 이들은 모두 당신의 것입니다. 앞서 말한 바와 같이 필요한 것을 즉시 얻을 수 없을 경우 이들은 피와 재산과 생명과 아이들까지도 당신에게 바칠 것입니다. 하지만 원하는 걸 거의 얻어 냈다면 당신을 배반할 것입니다. 그리고 전적으로 약속에만 의존하고 다른 예방 조치를 소홀히 한 군주는 파멸합니다. 위대함이나 고결한 정신이 아닌 돈으로 산 우정은 얻을 수는 있으나 보장되지는 않으며 정작 필요한 때에 의지할 수 없습니다. 인간은 사랑하는 사람을 화나게하는 것보다 두려워하는 사람을 화나게하는 일을 어렵게 생각합니다. 사랑은 의무의 연결로 보존되며 인간의 본성에 따라 자신의 이득을 위해 이 연결을 얼마든지 끊어 낼 수 있지만 두려움은 절대 실패할 수 없는 처벌에 대한 공포로 당신을 지켜 주기 때문입니다.”

  질문:위 글에서 주장하는 정치 철학은 중세 시대의 철학과 다음에 나열된 것 중 어떤 면에서 다른가요?

  선택지:
  1 - 군주가 자신의 권위를 주장하는 것이 정당하다는 개념을 받아들였다.
  2 - 윤리 또는 종교적 이념보다는 실용주의적 이념이었다.
  3 - 고전적인 과거를 돌아보는 것의 중요성을 강조했다.
  4 - 계층 간 경계를 초월하는 평등이라는 강력한 개념에 의존하지 않았다.

  정답: 2

  ### 문제 
  지문:
  {paragraph}

  질문: {question}

  <보기>:
  {question_plus}

  선택지: {choices}

  힌트:
  {hint}

  정답: